### ISSUE TITLE
Failed demo (Java version issues?)

### ISSUE THREAD

**Issue by rustandruin** [uwdata/termite-data-server#15]
I just installed the server and attempted to run the 20newsgroup demo. Mallet runs successfully, but then the process breaks down during the generation of the 20newgroups_mallet app. Here's the trace:

```
Creating app: 20newsgroups_mallet [apps/temp_20140703_174936_528732_1024]   
Creating folder: [apps/temp_20140703_174936_528732_1024/data]               
Creating folder: [apps/temp_20140703_174936_528732_1024/databases]          
Linking folder: [apps/temp_20140703_174936_528732_1024/models]              
Linking folder: [apps/temp_20140703_174936_528732_1024/views]               
Linking folder: [apps/temp_20140703_174936_528732_1024/controllers]         
Linking folder: [apps/temp_20140703_174936_528732_1024/static]              
Linking folder: [apps/temp_20140703_174936_528732_1024/modules]             
Creating file: [apps/temp_20140703_174936_528732_1024/__init__.py]          
Copying [data/demo/20newsgroups/corpus/corpus.db] --> [apps/temp_20140703_174936_528732_1024/databases/corpus.db]
Copying [data/demo/20newsgroups/corpus/corpus.txt] --> [apps/temp_20140703_174936_528732_1024/data/corpus.txt]
Extracting [data/demo/20newsgroups/corpus/corpus.txt] --> [apps/temp_20140703_174936_528732_1024/data/sentences.txt]
Exception in thread "main" java.lang.UnsupportedClassVersionError: corenlp_helpers/SentenceSplitter : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)                    
    at java.lang.ClassLoader.defineClass(ClassLoader.java:643)              
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)         
    at java.net.URLClassLoader.access$000(URLClassLoader.java:73)           
    at java.net.URLClassLoader$1.run(URLClassLoader.java:212)               
    at java.security.AccessController.doPrivileged(Native Method)           
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)           
    at java.lang.ClassLoader.loadClass(ClassLoader.java:323)                
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)        
    at java.lang.ClassLoader.loadClass(ClassLoader.java:268)                
Could not find the main class: corenlp_helpers.SentenceSplitter. Program will exit.
```

It looks like this is caused by a jar having been compiled using an earlier version of Java than I'm running (Java 2SE 8.0). Any ideas how to get around this?

**Comment by rustandruin** [comment]
Oh. I fixed it by going to the utils/corenlp directory and running make to recompile SentenceSplitter.jar
