### ISSUE TITLE
MALLET compatibility issues reported by Leo Claudino

### ISSUE THREAD

**Issue by jcchuang** [uwdata/termite-data-server#19]
Mallet has changed the doctopics.txt format so now it will have "#doc name topic proportion" rather than "#doc source topic proportion":

http://mallet.cs.umass.edu/dist/mallet-2.0.7.notes.txt

As a result, I'm getting this assertion error when reading in the model into the termite server:

An error occured while creating app: tweets_topics_140_k_5 [apps/tweets_topics_140_k_5]
Traceback (most recent call last):
  File "bin/read_treetm.py", line 92, in <module>
    main()
  File "bin/read_treetm.py", line 89, in main
    ImportMalletLDA( args.app_name, args.model_path, args.corpus_path, args.database_path, args.quiet, args.overwrite )
  File "bin/read_treetm.py", line 69, in ImportMalletLDA
    treetm_reader.Execute()
  File "/Users/claudino/Desktop/collaborations/with-CLIP/2014/summer/termite-data-server/bin/readers/TreeTMReader.py", line 30, in Execute
    self.ReadDocTopicMixtures()
  File "/Users/claudino/Desktop/collaborations/with-CLIP/2014/summer/termite-data-server/bin/readers/TreeTMReader.py", line 88, in ReadDocTopicMixtures
    assert line == "#doc source topic proportion ..."
AssertionError

Perhaps you want to change your assertion line to accommodate both cases?

**Comment by jcchuang** [comment]
Removed assertions in MalletReader and TreeTMReader in 6cccbeb743addceefaaf519436b0e74ff4ee0e92
