### ISSUE TITLE
Error occurred when I run the demos.

### ISSUE THREAD

**Issue by maoxuxiang** [uwdata/termite-data-server#20]
Hi there,

I use a Mac and I met the following problem when I run the first demo: ./demo.py 20newsgroups. And none of the build a topic demo can run successfully on my Mac. I followed the instruction to clone this repository onto my Mac already.

the error message as follows when I run ./demo.py 20newsgroups:

---

Build a topic model (mallet) using a demo dataset (20newsgroups)
  database = data/demo/20newsgroups/corpus
    corpus = data/demo/20newsgroups/corpus
     model = data/demo/20newsgroups/model-mallet
##        app = 20newsgroups_mallet

```
Available: data/demo/20newsgroups/corpus
Available: tools/mallet-2.0.7
Available: tools/mallet-2.0.7
Available: tools/corenlp-3.3.1
```

---

Training an LDA topic model using MALLET...
       corpus = data/demo/20newsgroups/corpus/corpus.txt
        model = data/demo/20newsgroups/model-mallet
  token_regex = \w{3,}
       topics = 20
##         iters = 1000

```
Already exists: data/demo/20newsgroups/model-mallet
```

---

Import a MALLET LDA topic model as a web2py application...
           app_name = 20newsgroups_mallet
           app_path = apps/20newsgroups_mallet
         model_path = data/demo/20newsgroups/model-mallet
    corpus_filename = data/demo/20newsgroups/corpus/corpus.txt
##   database_filename = data/demo/20newsgroups/corpus/corpus.db

Creating app: 20newsgroups_mallet [apps/temp_20141005_231611_222579_2092]
Creating folder: [apps/temp_20141005_231611_222579_2092/data]
Creating folder: [apps/temp_20141005_231611_222579_2092/databases]
Linking folder: [apps/temp_20141005_231611_222579_2092/models]
Linking folder: [apps/temp_20141005_231611_222579_2092/views]
Linking folder: [apps/temp_20141005_231611_222579_2092/controllers]
Linking folder: [apps/temp_20141005_231611_222579_2092/static]
Linking folder: [apps/temp_20141005_231611_222579_2092/modules]
Creating file: [apps/temp_20141005_231611_222579_2092/**init**.py]
Copying [data/demo/20newsgroups/corpus/corpus.db] --> [apps/temp_20141005_231611_222579_2092/databases/corpus.db]
Copying [data/demo/20newsgroups/corpus/corpus.txt] --> [apps/temp_20141005_231611_222579_2092/data/corpus.txt]
An error occured while creating app: 20newsgroups_mallet [apps/20newsgroups_mallet]
Traceback (most recent call last):
  File "bin/read_mallet.py", line 85, in <module>
    main()
  File "bin/read_mallet.py", line 82, in main
    ImportMalletLDA( args.app_name, args.model_path, args.corpus_path, args.database_path, args.quiet, args.overwrite )
  File "bin/read_mallet.py", line 47, in ImportMalletLDA
    shutil.copy( corpus_filename, app_corpus_filename )
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'data/demo/20newsgroups/corpus/corpus.txt'

Can you help me deal with this? 

And there is another question: I can start the data server and visualization client at the same time. What the next step I can do? I can only find a upload datasets option in the server page and after I upload the dataset, nothing happened to the client. Can you tell me how to output a figure just like your article ---- termite: : Visualization Techniques for Assessing Textual Topic Models by using the Mallet? I can't find any instruction document on the net. Thank you very much!!

**Comment by ldfu** [comment]
`demo.py` calls `bin/fetch_dataset.sh` which tries to curl the datasets from `http://homes.cs.washington.edu/~jcchuang/termite-datasets/$DEMO.zip`. however, the datasets are no longer there: http://homes.cs.washington.edu/~jcchuang/termite-datasets/

are the datasets available somewhere else?
