### ISSUE TITLE
How to create corpus.db

### ISSUE THREAD

**Issue by rcompton** [uwdata/termite-data-server#23]
I've successfully run the demos on Ubuntu 14.04. Now I'd like to visualize my own text. How do I create a corpus.db file?

**Comment by jcchuang** [comment]
If your input corpus is a single file (one document per line) or a folder (one document per file), you can create a corpus.db file by running bin/import_corpus.py.  For a single file, the script expects two values (tab-separated) on each line: a unique document ID and the body of the document.

**Comment by rcompton** [comment]
works great, thanks!

**Comment by YingHsuan** [comment]
Is there any setting before i run bin/import_corpus.py? 
I have 10 files(each document per file) in a forder, and i input this under termite-data-server-master in terminal : 

`bin/import_corpus.py cloudcomputing /Users/ying-hsuanlin/Desktop`

and i get this error messege : 

Traceback (most recent call last):
  File "bin/import_corpus.py", line 30, in <module>
    main()
  File "bin/import_corpus.py", line 27, in main
    ImportCorpus(args.corpus, args.database)
  File "bin/import_corpus.py", line 14, in ImportCorpus
    with Corpus_DB(database_path, isInit=True) as corpus_db:
  File "/Users/ying-hsuanlin/Downloads/termite-data-server-master/bin/db/Corpus_DB.py", line 28, in **init**
    self.db = DAL(Corpus_DB.CONNECTION, lazy_tables = not self.isInit, migrate_enabled = self.isInit, folder = path)
  File "web2py/gluon/dal.py", line 7867, in **init**
    raise RuntimeError("Failure to connect, tried %d times:\n%s" % (attempts, tb))
RuntimeError: Failure to connect, tried 5 times:
Traceback (most recent call last):
  File "web2py/gluon/dal.py", line 7845, in **init**
    self._adapter = ADAPTERS[self._dbname](**kwargs)
  File "web2py/gluon/dal.py", line 688, in __call__
    obj = super(AdapterMeta, cls).**call**(_args, *_kwargs)
  File "web2py/gluon/dal.py", line 2427, in **init**
    if do_connect: self.reconnect()
  File "web2py/gluon/dal.py", line 648, in reconnect
    self.connection = f()
  File "web2py/gluon/dal.py", line 2425, in connector
    return self.driver.Connection(dbpath, **driver_args)
OperationalError: unable to open database file

Thanks for help :)

**Comment by YingHsuan** [comment]
I fixed it by this :

`bin/import_corpus.py filePath fileName`

and it works , thank you.

**Comment by YingHsuan** [comment]
May i add a new column at doc table, and how? because i want to use doc title to show on the page, thanks.
