### ISSUE TITLE
Couldn't install the demo

### ISSUE THREAD

**Issue by hosamshahin** [uwdata/termite-data-server#30]
Hi,

  If anyone still maintaining this project, I could install the data server using 'make' command. But when I tried to install the first demo by using 'make demo' I got the following error:

Traceback (most recent call last):
  File "bin/read_mallet.py", line 85, in <module>
    main()
  File "bin/read_mallet.py", line 82, in main
    ImportMalletLDA( args.app_name, args.model_path, args.corpus_path, args.database_path, args.quiet, args.overwrite )
  File "bin/read_mallet.py", line 62, in ImportMalletLDA
    bow_computer.Execute()
  File "/home/hshahin/workspaces/termite-data-server/bin/db/BOW_ComputeStats.py", line 44, in Execute
    self.ComputeAndSaveSentenceLevelStatistics()
  File "/home/hshahin/workspaces/termite-data-server/bin/db/BOW_ComputeStats.py", line 132, in ComputeAndSaveSentenceLevelStatistics
    corpus = { docID : docTokens for docID, docTokens in reader }
  File "/home/hshahin/workspaces/termite-data-server/bin/db/BOW_ComputeStats.py", line 132, in <dictcomp>
    corpus = { docID : docTokens for docID, docTokens in reader }
  File "/home/hshahin/workspaces/termite-data-server/bin/db/BOW_ComputeStats.py", line 55, in ReadCorpus
    with open( filename, 'r' ) as f:
IOError: [Errno 2] No such file or directory: 'apps/temp_20160423_203727_860397_3120/data/sentences.txt'

Any idea how to solve this issue.

**Comment by bojeanson** [comment]
Check that you will find the reason. I think you should try with your own dataset.

https://github.com/uwdata/termite-data-server/issues/20
